// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpN_4R4JFen94tfWkiIdzoB49PPUMCyVM',
    appId: '1:964644452587:web:d9efa83ac6a4340e0ca6ae',
    messagingSenderId: '964644452587',
    projectId: 'tripchat-ab96e',
    authDomain: 'tripchat-ab96e.firebaseapp.com',
    storageBucket: 'tripchat-ab96e.firebasestorage.app',
    measurementId: 'G-PETXLYXPJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlDiR4ffAEXL5h_QVvmS8YN_C-DRRr_Ic',
    appId: '1:964644452587:android:5aae1ed6927a2f690ca6ae',
    messagingSenderId: '964644452587',
    projectId: 'tripchat-ab96e',
    storageBucket: 'tripchat-ab96e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0N2LyJcbgs7j5B5lTBglf6Wll4s3QrGs',
    appId: '1:964644452587:ios:5362a0d8d8ea66bd0ca6ae',
    messagingSenderId: '964644452587',
    projectId: 'tripchat-ab96e',
    storageBucket: 'tripchat-ab96e.firebasestorage.app',
    iosBundleId: 'com.example.tripchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0N2LyJcbgs7j5B5lTBglf6Wll4s3QrGs',
    appId: '1:964644452587:ios:5362a0d8d8ea66bd0ca6ae',
    messagingSenderId: '964644452587',
    projectId: 'tripchat-ab96e',
    storageBucket: 'tripchat-ab96e.firebasestorage.app',
    iosBundleId: 'com.example.tripchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpN_4R4JFen94tfWkiIdzoB49PPUMCyVM',
    appId: '1:964644452587:web:864cae92ea6c4a1c0ca6ae',
    messagingSenderId: '964644452587',
    projectId: 'tripchat-ab96e',
    authDomain: 'tripchat-ab96e.firebaseapp.com',
    storageBucket: 'tripchat-ab96e.firebasestorage.app',
    measurementId: 'G-ZWZJPX41L2',
  );
}
